### ISSUE TITLE
GetAllOperationModels() throw an error if _clientGeneratorSettings.ExcludedParameterNames is null 

### ISSUE THREAD

**Issue by alejsouza** [hemiaoio/nswag-ts-splitter#4]
![image](https://user-images.githubusercontent.com/14909123/88009398-cdab4b00-cae8-11ea-85ab-4d94d09ca26c.png)

![image](https://user-images.githubusercontent.com/14909123/88011139-ef0e3600-caec-11ea-915d-61bd7d840a99.png)

I've changed a little bit the constructor to validate is ExcludedParameterName is null

![image](https://user-images.githubusercontent.com/14909123/88011282-55935400-caed-11ea-84ec-0ec6e52846d4.png)

**I'm not sure if it is correct... but it works**

Regards_**

**Comment by hemiaoio** [comment]
I'll try it ,thanks.

**Comment by hemiaoio** [comment]
fixed.
